### ISSUE TITLE
Drush is required to install composer

### ISSUE THREAD

**Issue by mrleblanc101** [contentacms/contenta_docker#29]
Hi,
I've followed the instruction exactly but I get:
```
» docker-compose exec php composer run-script install:with-mysql
> scripts/install-mysql.sh
./scripts/install.sh: line 23: /var/www/vendor/drush/drush/drush
: No such file or directory
 ERROR  Drush is required to install Contenta CMS. Please install Contenta CMS using Composer. See http://www.contentacms.org/#install
Script scripts/install-mysql.sh handling the install:with-mysql event returned with error code 5
```
Drush is installed correctly in the vendor directory and the path to it in the script seem ok.
<img width="195" alt="capture d ecran le 2019-02-04 a 17 16 18" src="https://user-images.githubusercontent.com/17392251/52241011-99b27a80-28a0-11e9-8fcf-83f2bfd92b62.png">
Someone has an idea ?

**Comment by mrleblanc101** [comment]
Seem like it used my local composer. 
I had to composer global remove drush/drush
Is this a bug ? Shouldn't it use the composer in the docker container ?

**Comment by e0ipso** [comment]
Maybe @pcambra knows the answer to the question above ☝️.

**Comment by MykaMart** [comment]
I'm running into this issue as well. An inspection inside the running container confirms that it missing the nested /vender/drush/drush folder in /var/www. Anyone have any thoughts on how to remedy this?

**Comment by trevortwining** [comment]
Same issue here. Working on it today. If I resolve it, I'll submit a PR.

**Comment by pcambra** [comment]
I've updated both composer and moved to a more modern mode to install drush using cgr on https://github.com/contentacms/contenta_docker/commit/80a41a1f2506636e5fcd3daf3e45b7cc14165b9b, could you confirm this is fixed?

**Comment by MykaMart** [comment]
It was not, Contenta was still unable to find drush where it was expecting it during the install. 

I have created a <a href="https://github.com/contentacms/contenta_docker/pull/33">pull request</a> that solves the issue. The new Dockerfile creates the folder structure the installer is expecting and creates a symlink between the new folder and drush.

I have tested this fix and was able to complete the install.

**Comment by pcambra** [comment]
I must be missing something because according to the commit above and this https://github.com/contentacms/contenta_jsonapi/commit/a8cd75b38e42575460d2875f30a829eb186b21d2, there should not be a need for global drush, maybe we should explore why local drush is not being run
